/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Internal Health Full */
        get: operations["internal_health_full_internal_health_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email and password for a dashboard JWT.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current dashboard user.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Record logout audit for the current dashboard user.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/cro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook Cro */
        post: operations["webhook_cro_webhook_cro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/session/{channel}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_internal_session__channel___user_id__get"];
        put?: never;
        /** Save Session */
        post: operations["save_session_internal_session__channel___user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking */
        post: operations["create_booking_internal_booking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/cro-user/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Cro User */
        get: operations["get_latest_cro_user_internal_booking_cro_user_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/latest-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Pending */
        get: operations["get_latest_pending_internal_booking_latest_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/{request_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_internal_booking__request_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/{request_uid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Booking */
        post: operations["approve_booking_internal_booking__request_uid__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/{request_uid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Booking */
        post: operations["reject_booking_internal_booking__request_uid__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bookings
         * @description List bookings with optional status filter + pagination.
         */
        get: operations["list_bookings_api_bookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Booking
         * @description Get a single booking by request_uid.
         */
        get: operations["get_booking_api_bookings__request_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Booking
         * @description Check Google Calendar conflict, create event, mark approved, push patient LINE.
         */
        post: operations["approve_booking_api_bookings__request_uid__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Booking
         * @description Mark booking rejected, push patient LINE apology.
         */
        post: operations["reject_booking_api_bookings__request_uid__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveBooking */
        ApproveBooking: {
            /**
             * Calendar Event Id
             * @default
             */
            calendar_event_id: string;
            /**
             * Calendar Event Url
             * @default
             */
            calendar_event_url: string;
            /**
             * Approved By
             * @default cro
             */
            approved_by: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Start At
             * Format: date-time
             * @description ISO 8601 datetime (Asia/Bangkok). Slot start.
             */
            start_at: string;
            /**
             * Duration Min
             * @default 60
             */
            duration_min: number;
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Ok */
            ok: boolean;
            /** Calendar Event Id */
            calendar_event_id: string;
            /** Calendar Event Url */
            calendar_event_url: string;
        };
        /** BookingCreate */
        BookingCreate: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Symptom */
            symptom: string;
            /** Raw Summary */
            raw_summary?: {
                [key: string]: unknown;
            } | null;
        };
        /** BookingListItem */
        BookingListItem: {
            /** Request Uid */
            request_uid: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "cancelled" | "expired";
            /** Patient Name */
            patient_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Requested Datetime Text */
            requested_datetime_text?: string | null;
            /** Symptom */
            symptom?: string | null;
            /**
             * Booking Source
             * @enum {string}
             */
            booking_source: "line" | "phone" | "whatsapp" | "email" | "walkin";
            /**
             * Appointment Type
             * @enum {string}
             */
            appointment_type: "new" | "followup" | "procedure" | "consult";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BookingListResponse */
        BookingListResponse: {
            /** Data */
            data: components["schemas"]["BookingListItem"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** BookingOut */
        BookingOut: {
            /** Request Uid */
            request_uid: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "cancelled" | "expired";
            /** Patient Name */
            patient_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Requested Datetime Text */
            requested_datetime_text?: string | null;
            /** Symptom */
            symptom?: string | null;
            /**
             * Booking Source
             * @enum {string}
             */
            booking_source: "line" | "phone" | "whatsapp" | "email" | "walkin";
            /**
             * Appointment Type
             * @enum {string}
             */
            appointment_type: "new" | "followup" | "procedure" | "consult";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Channel */
            channel: string;
            /** External User Id */
            external_user_id: string;
            /** Requested Date */
            requested_date?: string | null;
            /** Requested Time */
            requested_time?: string | null;
            /** Service Type */
            service_type?: string | null;
            /** Doctor Code */
            doctor_code?: string | null;
            /** Duration Min */
            duration_min: number;
            /** Calendar Event Id */
            calendar_event_id?: string | null;
            /** Calendar Event Url */
            calendar_event_url?: string | null;
            /** Calendar Status */
            calendar_status: string;
            /** Assigned Doctor Id */
            assigned_doctor_id?: number | null;
            /** Patient Id */
            patient_id?: number | null;
            /** Notes */
            notes?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserOut"];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** RejectBooking */
        RejectBooking: {
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Rejected By
             * @default cro
             */
            rejected_by: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** SessionUpdate */
        SessionUpdate: {
            /**
             * Dify Conversation Id
             * @default
             */
            dify_conversation_id: string;
            /**
             * Current State
             * @default active
             */
            current_state: string;
        };
        /** SimpleOkResponse */
        SimpleOkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "doctor" | "cro";
            /** Specialty */
            specialty?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    internal_health_full_internal_health_full_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhook_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    webhook_cro_webhook_cro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_session_internal_session__channel___user_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                channel: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_session_internal_session__channel___user_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                channel: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_internal_booking_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_cro_user_internal_booking_cro_user_latest_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_pending_internal_booking_latest_pending_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_internal_booking__request_uid__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_booking_internal_booking__request_uid__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBooking"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_booking_internal_booking__request_uid__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBooking"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_bookings_get: {
        parameters: {
            query?: {
                status?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_api_bookings__request_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_booking_api_bookings__request_uid__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_booking_api_bookings__request_uid__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
