/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Internal Health Full */
        get: operations["internal_health_full_internal_health_full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email and password for a dashboard JWT.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current dashboard user.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Record logout audit for the current dashboard user.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Proxy dashboard AI chat to the service layer.
         */
        post: operations["chat_api_ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/cro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook Cro */
        post: operations["webhook_cro_webhook_cro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/session/{channel}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_internal_session__channel___user_id__get"];
        put?: never;
        /** Save Session */
        post: operations["save_session_internal_session__channel___user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking */
        post: operations["create_booking_internal_booking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/cro-user/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Cro User */
        get: operations["get_latest_cro_user_internal_booking_cro_user_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/latest-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Pending */
        get: operations["get_latest_pending_internal_booking_latest_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/{request_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_internal_booking__request_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/{request_uid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Booking */
        post: operations["approve_booking_internal_booking__request_uid__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/booking/{request_uid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Booking */
        post: operations["reject_booking_internal_booking__request_uid__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bookings
         * @description List bookings with optional status filter + pagination.
         */
        get: operations["list_bookings_api_bookings_get"];
        put?: never;
        /**
         * Create Booking
         * @description Create a manual booking from Web Dashboard using JWT auth.
         */
        post: operations["create_booking_api_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Booking
         * @description Get a single booking by request_uid.
         */
        get: operations["get_booking_api_bookings__request_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Booking
         * @description Check Google Calendar conflict, create event, mark approved, push patient LINE.
         */
        post: operations["approve_booking_api_bookings__request_uid__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Booking
         * @description Mark booking rejected, push patient LINE apology.
         */
        post: operations["reject_booking_api_bookings__request_uid__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{request_uid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Booking
         * @description Cancel an approved booking and remove its Google Calendar event.
         */
        post: operations["cancel_booking_api_bookings__request_uid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Patients
         * @description List patients with optional search (name/HN/phone) + pagination.
         */
        get: operations["list_patients_api_patients_get"];
        put?: never;
        /**
         * Create Patient
         * @description Create a new patient and auto-assign an HN.
         */
        post: operations["create_patient_api_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patient
         * @description Get a single patient by id.
         */
        get: operations["get_patient_api_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Patient
         * @description Update patient profile fields. Only fields present in payload are changed.
         */
        patch: operations["update_patient_api_patients__patient_id__patch"];
        trace?: never;
    };
    "/api/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Calendar Events
         * @description List Google Calendar events for the dashboard calendar.
         */
        get: operations["list_calendar_events_api_calendar_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Patient Reports
         * @description List reports for one patient.
         */
        get: operations["list_patient_reports_api_patients__patient_id__reports_get"];
        put?: never;
        /**
         * Upload Patient Report
         * @description Upload one patient report file and store extracted text when available.
         */
        post: operations["upload_patient_report_api_patients__patient_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Get report metadata and extracted text.
         */
        get: operations["get_report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report File
         * @description Download or preview the stored report file.
         */
        get: operations["get_report_file_api_reports__report_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Report Analyses
         * @description List AI analyses for a report.
         */
        get: operations["list_report_analyses_api_reports__report_id__analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Report
         * @description Run Dify analysis for a report.
         */
        post: operations["analyze_report_api_reports__report_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/analyses/{analysis_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Report Triage
         * @description Confirm the final triage decision for one analysis.
         */
        post: operations["decide_report_triage_api_reports_analyses__analysis_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisListResponse */
        AnalysisListResponse: {
            /** Data */
            data: components["schemas"]["AnalysisOut"][];
        };
        /** AnalysisOut */
        AnalysisOut: {
            /** Id */
            id: number;
            /** Report Id */
            report_id: number;
            /** Requested By */
            requested_by?: number | null;
            /** Dify Conversation Id */
            dify_conversation_id?: string | null;
            /** Summary Text */
            summary_text: string;
            /**
             * Triage Decision
             * @enum {string}
             */
            triage_decision: "accept" | "reject" | "review" | "pending";
            /** Decided By */
            decided_by?: number | null;
            /** Decided At */
            decided_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Ok */
            ok: boolean;
            analysis: components["schemas"]["AnalysisOut"];
        };
        /** ApproveBooking */
        ApproveBooking: {
            /**
             * Calendar Event Id
             * @default
             */
            calendar_event_id: string;
            /**
             * Calendar Event Url
             * @default
             */
            calendar_event_url: string;
            /**
             * Approved By
             * @default cro
             */
            approved_by: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Start At
             * Format: date-time
             * @description ISO 8601 datetime (Asia/Bangkok). Slot start.
             */
            start_at: string;
            /**
             * Duration Min
             * @default 60
             */
            duration_min: number;
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Ok */
            ok: boolean;
            /** Calendar Event Id */
            calendar_event_id: string;
            /** Calendar Event Url */
            calendar_event_url: string;
            /** Patient Id */
            patient_id: number;
            /** Hn */
            hn?: string | null;
        };
        /** Body_upload_patient_report_api_patients__patient_id__reports_post */
        Body_upload_patient_report_api_patients__patient_id__reports_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Title */
            title: string;
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "lab" | "imaging" | "history" | "prescription" | "referral" | "other";
            /**
             * Source
             * @default web
             * @enum {string}
             */
            source: "web" | "line" | "email" | "whatsapp" | "walkin";
            /** Notes */
            notes?: string | null;
        };
        /** BookingCreate */
        BookingCreate: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Symptom */
            symptom: string;
            /** Raw Summary */
            raw_summary?: {
                [key: string]: unknown;
            } | null;
        };
        /** BookingCreateRequest */
        BookingCreateRequest: {
            /** Patient Name */
            patient_name: string;
            /** Phone */
            phone: string;
            /** Requested Date */
            requested_date: string;
            /** Requested Time */
            requested_time: string;
            /**
             * Symptom
             * @default
             */
            symptom: string;
            /**
             * Booking Source
             * @default phone
             * @enum {string}
             */
            booking_source: "line" | "phone" | "whatsapp" | "email" | "walkin";
        };
        /** BookingCreateResponse */
        BookingCreateResponse: {
            /** Ok */
            ok: boolean;
            /** Request Uid */
            request_uid: string;
        };
        /** BookingListItem */
        BookingListItem: {
            /** Request Uid */
            request_uid: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "cancelled" | "expired";
            /** Patient Name */
            patient_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Requested Datetime Text */
            requested_datetime_text?: string | null;
            /** Symptom */
            symptom?: string | null;
            /**
             * Booking Source
             * @enum {string}
             */
            booking_source: "line" | "phone" | "whatsapp" | "email" | "walkin";
            /**
             * Appointment Type
             * @enum {string}
             */
            appointment_type: "new" | "followup" | "procedure" | "consult";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BookingListResponse */
        BookingListResponse: {
            /** Data */
            data: components["schemas"]["BookingListItem"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** BookingOut */
        BookingOut: {
            /** Request Uid */
            request_uid: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "cancelled" | "expired";
            /** Patient Name */
            patient_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Requested Datetime Text */
            requested_datetime_text?: string | null;
            /** Symptom */
            symptom?: string | null;
            /**
             * Booking Source
             * @enum {string}
             */
            booking_source: "line" | "phone" | "whatsapp" | "email" | "walkin";
            /**
             * Appointment Type
             * @enum {string}
             */
            appointment_type: "new" | "followup" | "procedure" | "consult";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Channel */
            channel: string;
            /** External User Id */
            external_user_id: string;
            /** Requested Date */
            requested_date?: string | null;
            /** Requested Time */
            requested_time?: string | null;
            /** Service Type */
            service_type?: string | null;
            /** Doctor Code */
            doctor_code?: string | null;
            /** Duration Min */
            duration_min: number;
            /** Calendar Event Id */
            calendar_event_id?: string | null;
            /** Calendar Event Url */
            calendar_event_url?: string | null;
            /** Calendar Status */
            calendar_status: string;
            /** Assigned Doctor Id */
            assigned_doctor_id?: number | null;
            /** Patient Id */
            patient_id?: number | null;
            /** Notes */
            notes?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CalendarEventOut */
        CalendarEventOut: {
            /** Id */
            id: string;
            /** Summary */
            summary: string;
            /** Description */
            description?: string | null;
            /** Html Link */
            html_link?: string | null;
            /** Status */
            status?: string | null;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** All Day */
            all_day: boolean;
        };
        /** CalendarEventsResponse */
        CalendarEventsResponse: {
            /** Data */
            data: components["schemas"]["CalendarEventOut"][];
        };
        /** CancelRequest */
        CancelRequest: {
            /**
             * Reason
             * @default Cancelled by CRO
             */
            reason: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * Conversation Id
             * @default
             */
            conversation_id: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Conversation Id */
            conversation_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserOut"];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PatientCreateRequest */
        PatientCreateRequest: {
            /** Display Name */
            display_name: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Dob */
            dob?: string | null;
            /** Gender */
            gender?: ("male" | "female" | "other" | "unknown") | null;
            /** Notes */
            notes?: string | null;
        };
        /** PatientListItem */
        PatientListItem: {
            /** Id */
            id: number;
            /** Hn */
            hn?: string | null;
            /** Display Name */
            display_name: string;
            /** Phone */
            phone?: string | null;
            /** Gender */
            gender?: ("male" | "female" | "other" | "unknown") | null;
            /** Latest Visit At */
            latest_visit_at?: string | null;
            /**
             * Total Bookings
             * @default 0
             */
            total_bookings: number;
            /**
             * Total Reports
             * @default 0
             */
            total_reports: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PatientListResponse */
        PatientListResponse: {
            /** Data */
            data: components["schemas"]["PatientListItem"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** PatientOut */
        PatientOut: {
            /** Id */
            id: number;
            /** Hn */
            hn?: string | null;
            /** Display Name */
            display_name: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Dob */
            dob?: string | null;
            /** Gender */
            gender?: ("male" | "female" | "other" | "unknown") | null;
            /** Notes */
            notes?: string | null;
            /** Created By */
            created_by?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PatientUpdateRequest */
        PatientUpdateRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Dob */
            dob?: string | null;
            /** Gender */
            gender?: ("male" | "female" | "other" | "unknown") | null;
            /** Notes */
            notes?: string | null;
        };
        /** RejectBooking */
        RejectBooking: {
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Rejected By
             * @default cro
             */
            rejected_by: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ReportListItem */
        ReportListItem: {
            /** Id */
            id: number;
            /** Patient Id */
            patient_id: number;
            /**
             * Source
             * @enum {string}
             */
            source: "web" | "line" | "email" | "whatsapp" | "walkin";
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "lab" | "imaging" | "history" | "prescription" | "referral" | "other";
            /** Title */
            title: string;
            /** File Mime */
            file_mime?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Has File */
            has_file: boolean;
            /** Has Extracted Text */
            has_extracted_text: boolean;
            /** Latest Analysis At */
            latest_analysis_at?: string | null;
            /** Uploaded By */
            uploaded_by?: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Data */
            data: components["schemas"]["ReportListItem"][];
        };
        /** ReportOut */
        ReportOut: {
            /** Id */
            id: number;
            /** Patient Id */
            patient_id: number;
            /**
             * Source
             * @enum {string}
             */
            source: "web" | "line" | "email" | "whatsapp" | "walkin";
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "lab" | "imaging" | "history" | "prescription" | "referral" | "other";
            /** Title */
            title: string;
            /** File Mime */
            file_mime?: string | null;
            /** File Size */
            file_size?: number | null;
            /** Has File */
            has_file: boolean;
            /** Has Extracted Text */
            has_extracted_text: boolean;
            /** Latest Analysis At */
            latest_analysis_at?: string | null;
            /** Uploaded By */
            uploaded_by?: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Extracted Text */
            extracted_text?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReportUploadResponse */
        ReportUploadResponse: {
            /** Ok */
            ok: boolean;
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Has Extracted Text */
            has_extracted_text: boolean;
        };
        /** SessionUpdate */
        SessionUpdate: {
            /**
             * Dify Conversation Id
             * @default
             */
            dify_conversation_id: string;
            /**
             * Current State
             * @default active
             */
            current_state: string;
        };
        /** SimpleOkResponse */
        SimpleOkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** TriageDecideRequest */
        TriageDecideRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject" | "review";
            /** Note */
            note?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "doctor" | "cro";
            /** Specialty */
            specialty?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    internal_health_full_internal_health_full_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_api_ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    webhook_cro_webhook_cro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_session_internal_session__channel___user_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                channel: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_session_internal_session__channel___user_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                channel: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_internal_booking_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_cro_user_internal_booking_cro_user_latest_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_pending_internal_booking_latest_pending_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_internal_booking__request_uid__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_booking_internal_booking__request_uid__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBooking"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_booking_internal_booking__request_uid__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string | null;
            };
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBooking"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_api_bookings_get: {
        parameters: {
            query?: {
                status?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_api_bookings__request_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_booking_api_bookings__request_uid__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_booking_api_bookings__request_uid__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_api_bookings__request_uid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patients_api_patients_get: {
        parameters: {
            query?: {
                search?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_api_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_api_patients__patient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calendar_events_api_calendar_events_get: {
        parameters: {
            query: {
                /** @description ISO 8601 range start */
                time_min: string;
                /** @description ISO 8601 range end */
                time_max: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patient_reports_api_patients__patient_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_patient_report_api_patients__patient_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_patient_report_api_patients__patient_id__reports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_file_api_reports__report_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_report_analyses_api_reports__report_id__analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_report_api_reports__report_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_report_triage_api_reports_analyses__analysis_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageDecideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
