// Demo-only sample uploaded lab reports for the /reports (ผลแล็บ) workspace.
// Shown ONLY when the page is in demo mode (?demo=1 or the "ดูตัวอย่างข้อมูล" button),
// behind a clear "ไม่ใช่ข้อมูลจริง" banner — never mixed into live data.
// Mirrors lib/mockLabResults.ts / lib/mockBiomarkers.ts pattern. No backend involved.
import type { WorkspaceReport } from '../hooks/useReportsWorkspace'

export const MOCK_WORKSPACE_REPORTS: WorkspaceReport[] = [
  {
    report_id: 9001,
    patient_id: 101,
    title: 'CBC + Metabolic Panel (ผลเลือดรวม)',
    report_type: 'lab',
    source: 'email',
    uploaded_at: '2026-07-08T09:12:00',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'นายสมชาย ใจดี',
    hn: 'HN-2019-001',
    latest_decision: 'review',
    analysis_at: '2026-07-08T09:20:00',
  },
  {
    report_id: 9002,
    patient_id: 102,
    title: 'Lipid Profile + HbA1c',
    report_type: 'lab',
    source: 'web',
    uploaded_at: '2026-07-08T11:40:00',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'นางสาวมาลี ศรีสุข',
    hn: 'HN-2020-014',
    latest_decision: 'pending',
    analysis_at: '2026-07-08T11:45:00',
  },
  {
    report_id: 9003,
    patient_id: 103,
    title: 'Thyroid Panel (TSH, Free T3/T4)',
    report_type: 'lab',
    source: 'line',
    uploaded_at: '2026-07-07T15:05:00',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'นายอนุชา พงษ์เจริญ',
    hn: 'HN-2018-102',
    latest_decision: 'accept',
    analysis_at: '2026-07-07T15:12:00',
  },
  {
    report_id: 9004,
    patient_id: 104,
    title: 'Chest X-ray (ฟิล์มปอด)',
    report_type: 'imaging',
    source: 'walkin',
    uploaded_at: '2026-07-07T10:22:00',
    notes: null,
    assigned_doctor_id: null,
    assigned_doctor_name: null,
    has_file: 1,
    patient_name: 'นางวิไล ทองมาก',
    hn: 'HN-2017-077',
    latest_decision: 'reject',
    analysis_at: '2026-07-07T10:30:00',
  },
  {
    report_id: 9005,
    patient_id: 105,
    title: 'Vitamin D + hs-CRP + Ferritin',
    report_type: 'lab',
    source: 'email',
    uploaded_at: '2026-07-09T08:02:00',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'นายเดชา ก้องไกล',
    hn: 'HN-2019-050',
    latest_decision: 'no_analysis',
    analysis_at: null,
  },
  {
    report_id: 9006,
    patient_id: 106,
    title: 'Hormone Panel (Testosterone, Estradiol)',
    report_type: 'lab',
    source: 'web',
    uploaded_at: '2026-07-09T09:35:00',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'นางสาวปาริชาต ใจงาม',
    hn: 'HN-2024-201',
    latest_decision: 'pending',
    analysis_at: '2026-07-09T09:41:00',
  },
  {
    report_id: 9007,
    patient_id: 107,
    title: 'Liver Function Test (SGOT/SGPT)',
    report_type: 'lab',
    source: 'line',
    uploaded_at: '2026-07-06T13:50:00',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'นายกิตติ วัฒนชัย',
    hn: 'HN-2021-033',
    latest_decision: 'accept',
    analysis_at: '2026-07-06T14:00:00',
  },
  {
    report_id: 9008,
    patient_id: 108,
    title: 'Food Sensitivity IgG Panel',
    report_type: 'lab',
    source: 'email',
    uploaded_at: '2026-07-09T07:18:00',
    notes: null,
    assigned_doctor_id: null,
    assigned_doctor_name: null,
    has_file: 1,
    patient_name: 'นางสุดา เจริญพร',
    hn: 'HN-2023-090',
    latest_decision: 'review',
    analysis_at: '2026-07-09T07:25:00',
  },
]
