// DEMO-ONLY sample data for the doctor's กล่องเอกสาร page. Shown only when the
// page is opened with ?demo=1, behind a visible "โหมดตัวอย่าง" banner, so it can
// never be mistaken for real patient data. Safe to delete once the office backend
// has real CRO-assigned reports to show. Shape matches WorkspaceReport exactly.
import type { WorkspaceReport } from '../hooks/useReportsWorkspace'

export const MOCK_DOCUMENTS: WorkspaceReport[] = [
  {
    report_id: 9001,
    patient_id: 101,
    title: 'ผล CBC + Electrolytes',
    report_type: 'lab',
    source: 'email',
    uploaded_at: '2026-07-08T02:10:00Z',
    notes: 'CRO อัปจากอีเมลแล็บภายนอก',
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'สมชาย ใจดี',
    hn: 'HN-2019-001',
    latest_decision: null,
    analysis_at: null,
  },
  {
    report_id: 9002,
    patient_id: 102,
    title: 'ผลไขมันในเลือด (Lipid Panel)',
    report_type: 'lab',
    source: 'web',
    uploaded_at: '2026-07-07T09:30:00Z',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'สมหญิง มีสุข',
    hn: 'HN-2020-014',
    latest_decision: 'review',
    analysis_at: '2026-07-07T10:00:00Z',
  },
  {
    report_id: 9003,
    patient_id: 103,
    title: 'ผลน้ำตาลสะสม (HbA1c)',
    report_type: 'lab',
    source: 'walkin',
    uploaded_at: '2026-07-06T04:00:00Z',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 0,
    patient_name: 'ประยุทธ์ แข็งแรง',
    hn: 'HN-2021-008',
    latest_decision: 'accept',
    analysis_at: '2026-07-06T05:00:00Z',
  },
  {
    report_id: 9101,
    patient_id: 101,
    title: 'บันทึกการตรวจร่างกาย (พยาบาล)',
    report_type: 'history',
    source: 'web',
    uploaded_at: '2026-07-08T01:20:00Z',
    notes: 'พยาบาลจดสัญญาณชีพ + ซักประวัติ CRO รวมเป็นไฟล์',
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'สมชาย ใจดี',
    hn: 'HN-2019-001',
    latest_decision: null,
    analysis_at: null,
  },
  {
    report_id: 9102,
    patient_id: 104,
    title: 'ประวัติซักอาการก่อนพบแพทย์',
    report_type: 'history',
    source: 'line',
    uploaded_at: '2026-07-05T07:45:00Z',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'วิภา สดใส',
    hn: 'HN-2022-031',
    latest_decision: 'accept',
    analysis_at: '2026-07-05T08:30:00Z',
  },
  {
    report_id: 9201,
    patient_id: 102,
    title: 'ผล X-ray ทรวงอก',
    report_type: 'imaging',
    source: 'email',
    uploaded_at: '2026-07-07T06:15:00Z',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'สมหญิง มีสุข',
    hn: 'HN-2020-014',
    latest_decision: null,
    analysis_at: null,
  },
  {
    report_id: 9301,
    patient_id: 103,
    title: 'ใบสั่งยาต่อเนื่อง (เบาหวาน)',
    report_type: 'prescription',
    source: 'web',
    uploaded_at: '2026-07-04T03:00:00Z',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'ประยุทธ์ แข็งแรง',
    hn: 'HN-2021-008',
    latest_decision: 'reject',
    analysis_at: '2026-07-04T04:00:00Z',
  },
  {
    report_id: 9401,
    patient_id: 104,
    title: 'ใบส่งตัวพบแพทย์เฉพาะทางหัวใจ',
    report_type: 'referral',
    source: 'walkin',
    uploaded_at: '2026-07-03T08:00:00Z',
    notes: null,
    assigned_doctor_id: 1,
    assigned_doctor_name: 'Dr. AI BBH',
    has_file: 1,
    patient_name: 'วิภา สดใส',
    hn: 'HN-2022-031',
    latest_decision: null,
    analysis_at: null,
  },
]
